export const movementAliasMap: Record<string, string> = {
  "bbjo": "Burpee Box Jump Over",
  "burpee box jump over": "Burpee Box Jump Over",
  "burpee box step over": "Burpee Box Jump Over",
  "bbj": "Burpee Box Jump",
  "bbj over": "Burpee Box Jump Over",
  "wb": "Wall Ball",
  "wall balls": "Wall Ball",
  "wall ball": "Wall Ball",
  "wbs": "Wall Ball",
  "du": "Double Under",
  "double under": "Double Under",
  "double unders": "Double Under",
  "su": "Single Under",
  "single unders": "Single Under",
  "kb": "Kettlebell Swing",
  "kb swing": "Kettlebell Swing",
  "kettlebell swing": "Kettlebell Swing",
  "kb swing russian": "Kettlebell Swing",
  "kb swing americano": "Kettlebell Swing",
  "kbs": "Kettlebell Swing",
  "kettlebell lunges": "Kettlebell Lunge",
  "kb lunge": "Kettlebell Lunge",
  "kb lunges": "Kettlebell Lunge",
  "goblet lunge": "Kettlebell Lunge",
  "goblet step up": "Kettlebell Step Up",
  "goblet step ups": "Kettlebell Step Up",
  "step up": "Step Up",
  "step ups": "Step Up",
  "row": "Row",
  "rower": "Row",
  "ski": "SkiErg",
  "ski erg": "SkiErg",
  "bike": "BikeErg",
  "assault": "Assault Bike",
  "air bike": "Assault Bike",
  "run": "Run",
  "correr": "Run",
  "trail": "Run",
  "burpee": "Burpee",
  "burpees": "Burpee",
  "t2b": "Toes To Bar",
  "toes to bar": "Toes To Bar",
  "pull up": "Pull Up",
  "pull-ups": "Pull Up",
  "push up": "Push Up",
  "push-ups": "Push Up",
  "dl": "Deadlift",
  "deadlift": "Deadlift",
  "dl heavy": "Deadlift",
  "clean": "Clean",
  "power clean": "Power Clean",
  "snatch": "Snatch",
  "box jump": "Box Jump",
  "box jumps": "Box Jump"
};

export const movementKeywords: Array<{ keyword: string; target: string }> = [
  { keyword: "swing", target: "Kettlebell Swing" },
  { keyword: "goblet", target: "Kettlebell Lunge" },
  { keyword: "step up", target: "Step Up" },
  { keyword: "wall ball", target: "Wall Ball" },
  { keyword: "double under", target: "Double Under" },
  { keyword: "burpee", target: "Burpee" },
  { keyword: "row", target: "Row" },
  { keyword: "ski", target: "SkiErg" },
  { keyword: "run", target: "Run" },
  { keyword: "bike", target: "BikeErg" },
  { keyword: "clean", target: "Clean" },
  { keyword: "snatch", target: "Snatch" },
  { keyword: "deadlift", target: "Deadlift" },
  { keyword: "pull up", target: "Pull Up" },
  { keyword: "push up", target: "Push Up" }
];
